### ISSUE TITLE
waterfull without Promise implementation

### ISSUE THREAD

**Issue by terinjokes** [notjrbauer/promise.waterfall#4]
You can implement this module without having a dependency on any Promise implementation, instead solely using the Promise implementations used by the user. See [`promise-series`](https://github.com/terinjokes/promise-series/blob/79c50d56dda60e3910e6327680bb8745c1d13012/index.js#L31-L34).

**Comment by notjrbauer** [comment]
thanks @terinjokes, I've removed the promise dependency
