### ISSUE TITLE
Allow Promises as function parameters

### ISSUE THREAD

**Issue by netpoetica** [notjrbauer/promise.waterfall#8]
I'm not sure if this is something you're interested in, but this waterfall implementation IMHO is a little bit unfriendly for promises. Per example:

```
promiseWaterfall([
  new Promise(function one (resolve, reject) {
   	console.log('one');
    	resolve('one');
  }),
  new Promise(function two (resolve, reject) {
    	console.log('two');
    	resolve('two');
  })
])
.then(function () {
  console.log('done!', arguments);
})
.catch(function (e) {
  console.log(e);
});
```

You will get some errors because promiseWaterfall expects a callback function that returns a promise rather than just a promise. Whereas Promise.all handles this (in parallel of course) without any issue:

```
Promise.all([
  new Promise(function one (resolve, reject) {
   	console.log('one');
    	resolve('one');
  }),
  new Promise(function two (resolve, reject) {
    	console.log('two');
    	resolve('two');
  })
])
.then(function () {
  console.log('done!', arguments);
})
.catch(function (e) {
  console.log(e);
});
```

Shouldn't this library be able to handle having promises passed first-class? I think you could do this by doing a check before trying to execute it as a function.

Cheers!

**Comment by raineorshine** [comment]
@netpoetica You have omitted one crucial point: if you have *just* a promise instance, it is already executing! So they will end up being run in parallel anyway. You need to wrap them in a function to defer execution.

**Comment by netpoetica** [comment]
So then because this particular control flow mechanism requires things to be executed sequentially, that is why the argument *must* be a function that  runs and returns a promise, yah?

Makes sense - I was just going by MDN documentation on Promise.all, where is OK/acceptable for promises to be run in parallel and return at any time.

**Comment by netpoetica** [comment]
@notjrbauer Maybe in the README if you show what the addOne function looks like in the example, it will help clarify?

**Comment by raineorshine** [comment]
@netpoetica That would be a great clarification! Would you mind submitting a pull request to the README?

**Comment by notjrbauer** [comment]
Hey everyone! Sorry for neglecting this repo. I've updated the readme to be a bit more specific (95bb1e5f).
